# -------------------
# Secure Redis Config
# -------------------

#  Only allow local (container) access
bind 127.0.0.1

# Enable protected mode (default: yes)
protected-mode yes

# Require password for authentication
requirepass StrongRedisPass123!

# Rename or disable dangerous commands
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG b840fc02d524045429941cc15f59e41cb7be6c52

# Limit max memory (example: 256mb, prevents DoS attacks by memory exhaustion)
maxmemory 256mb
maxmemory-policy allkeys-lru
